/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;


import javax.swing.JOptionPane;
import Transportation.AirTaxi_Reservation;
import Transportation.Monorail_Reservation;
import DigialID.Digital_ID;
import Login.handleUsers;
import Egypt_2030_Text.Egypt2030_ar;
import Egypt_2030_Text.Egypt2030_en;
import Egypt_2030_Text.Egypt2030_es;
import Egypt_2030_Text.Egypt2030_fr;
import Language_Settings.LanguageSettings;
import Tourist_Site_Booking.GEM_Booking;
import My_Tickets.My_Tickets_Form;

/**
 *
 * @author memo1
 */
public class MyHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyHome.class.getName());

    /**
     * Creates new form MyHome
     */
    private String user_name;
    private int user_id;
    
    public MyHome(String user_name, int user_id) {
        this.user_name = user_name;
        this.user_id = user_id;
        initComponents();
        jLabel1.setText("Welcome, " + user_name + "!");
    }
    
    public MyHome(String user_name) {
        this.user_name = user_name;
        initComponents();
        jLabel1.setText("Welcome, " + user_name + "!");
    }
    
    public MyHome() {
        initComponents();
        jLabel1.setText("Hello!"); // default text if no username is provided
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Egypt_Vision_2030_btn = new javax.swing.JButton();
        TouristSiteTickets_btn = new javax.swing.JButton();
        AirTaxiReservation_btn = new javax.swing.JButton();
        MyTickets_btn = new javax.swing.JButton();
        MonorailBooking_btn = new javax.swing.JButton();
        PrefLang_btn = new javax.swing.JButton();
        DigitalID_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Hello" + user_name);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/president_new_rep.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/egypt-2030.png"))); // NOI18N

        Egypt_Vision_2030_btn.setBackground(new java.awt.Color(232, 44, 48));
        Egypt_Vision_2030_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Egypt_Vision_2030.png"))); // NOI18N
        Egypt_Vision_2030_btn.setBorder(null);
        Egypt_Vision_2030_btn.setBorderPainted(false);
        Egypt_Vision_2030_btn.setFocusPainted(false);
        Egypt_Vision_2030_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Egypt_Vision_2030_btnActionPerformed(evt);
            }
        });

        TouristSiteTickets_btn.setBackground(new java.awt.Color(23, 180, 196));
        TouristSiteTickets_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Tourist_Site_Tickets.png"))); // NOI18N
        TouristSiteTickets_btn.setMaximumSize(new java.awt.Dimension(252, 210));
        TouristSiteTickets_btn.setMinimumSize(new java.awt.Dimension(252, 210));
        TouristSiteTickets_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TouristSiteTickets_btnActionPerformed(evt);
            }
        });

        AirTaxiReservation_btn.setBackground(new java.awt.Color(255, 160, 24));
        AirTaxiReservation_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Air_Taxi_Reservation.png"))); // NOI18N
        AirTaxiReservation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirTaxiReservation_btnActionPerformed(evt);
            }
        });

        MyTickets_btn.setBackground(new java.awt.Color(143, 54, 234));
        MyTickets_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/My_Tickets.png"))); // NOI18N
        MyTickets_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTickets_btnActionPerformed(evt);
            }
        });

        MonorailBooking_btn.setBackground(new java.awt.Color(254, 205, 30));
        MonorailBooking_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Monorail_Booking.png"))); // NOI18N
        MonorailBooking_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonorailBooking_btnActionPerformed(evt);
            }
        });

        PrefLang_btn.setBackground(new java.awt.Color(14, 149, 228));
        PrefLang_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Language_Settings.png"))); // NOI18N
        PrefLang_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrefLang_btnActionPerformed(evt);
            }
        });

        DigitalID_btn.setText("Digital ID");
        DigitalID_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitalID_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(460, 460, 460)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(797, 797, 797)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TouristSiteTickets_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Egypt_Vision_2030_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AirTaxiReservation_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MyTickets_btn))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MonorailBooking_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrefLang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DigitalID_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DigitalID_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Egypt_Vision_2030_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AirTaxiReservation_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(MonorailBooking_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MyTickets_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TouristSiteTickets_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrefLang_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AirTaxiReservation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirTaxiReservation_btnActionPerformed
        // TODO add your handling code here:
        AirTaxi_Reservation airtaxiForm = new AirTaxi_Reservation(user_id);
        airtaxiForm.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_AirTaxiReservation_btnActionPerformed

    private void TouristSiteTickets_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TouristSiteTickets_btnActionPerformed
        // TODO add your handling code here:
        GEM_Booking gembookform = new GEM_Booking(user_id);
        gembookform.setVisible(true);
        // this.setVisible(false);
        
    }//GEN-LAST:event_TouristSiteTickets_btnActionPerformed

    private void DigitalID_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitalID_btnActionPerformed
        // TODO add your handling code here:
        String userIdStr = String.valueOf(user_id);

        // Fetch National ID safely
        String nationalId = handleUsers.getNationalIdByUserId(user_id);
        if (nationalId == null || nationalId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: National ID not found for user.");
            return; // stop execution
        }

        // Hash the combination
        String userDigitalIdHashed = handleUsers.hashPassword(userIdStr + nationalId);

        if (userDigitalIdHashed == null || userDigitalIdHashed.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Failed to generate digital ID.");
            return;
        }
        
        System.out.println(userDigitalIdHashed);

        // Create Digital_ID window safely
        Digital_ID digitalUserIdWindow = new Digital_ID(userDigitalIdHashed);
        digitalUserIdWindow.setVisible(true);
        
    }//GEN-LAST:event_DigitalID_btnActionPerformed

    private void Egypt_Vision_2030_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Egypt_Vision_2030_btnActionPerformed
        // TODO add your handling code here:
        String user_pref_lang = handleUsers.getUserPrefLanguage(user_id);
        
        if(user_pref_lang.equals("English")) {
            Egypt2030_en english_window = new Egypt2030_en();
            english_window.setVisible(true);
        } else if (user_pref_lang.equals("Arabic")) {
            Egypt2030_ar arabic_window = new Egypt2030_ar();
            arabic_window.setVisible(true);
        } else if (user_pref_lang.equals("French")) {
            Egypt2030_fr french_window = new Egypt2030_fr();
            french_window.setVisible(true);
        } else if (user_pref_lang.equals("Spanish")) {
            Egypt2030_es spanish_window = new Egypt2030_es();
            spanish_window.setVisible(true);
        }
        
    }//GEN-LAST:event_Egypt_Vision_2030_btnActionPerformed

    private void PrefLang_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrefLang_btnActionPerformed
        // TODO add your handling code here:
        LanguageSettings update_lang_form = new LanguageSettings(user_id);
        update_lang_form.setVisible(true);
        
    }//GEN-LAST:event_PrefLang_btnActionPerformed

    private void MonorailBooking_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonorailBooking_btnActionPerformed
        // TODO add your handling code here:
        Monorail_Reservation airtaxiForm = new Monorail_Reservation(user_id);
        airtaxiForm.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_MonorailBooking_btnActionPerformed

    private void MyTickets_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTickets_btnActionPerformed
        // TODO add your handling code here:
        My_Tickets_Form myTicketsForm = new My_Tickets_Form(user_id);
        myTicketsForm.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_MyTickets_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AirTaxiReservation_btn;
    private javax.swing.JButton DigitalID_btn;
    private javax.swing.JButton Egypt_Vision_2030_btn;
    private javax.swing.JButton MonorailBooking_btn;
    private javax.swing.JButton MyTickets_btn;
    private javax.swing.JButton PrefLang_btn;
    private javax.swing.JButton TouristSiteTickets_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
