/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Transportation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import Login.OracleConnection; // your existing DB connection class

import javax.swing.JOptionPane;

/**
 *
 * @author memo1
 */
public class AirTaxi_Reservation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AirTaxi_Reservation.class.getName());

    /**
     * Creates new form Monorail_Reservation
     */
    
    private int user_id;
    public AirTaxi_Reservation(int user_id) {
        this.user_id = user_id;
        initComponents();
    }
    
    public AirTaxi_Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_PaymentMethod = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user_OriginStation = new javax.swing.JComboBox<>();
        user_DestinationStation = new javax.swing.JComboBox<>();
        user_DepartureDate = new javax.swing.JTextField();
        user_DepartureTime = new javax.swing.JComboBox<>();
        CheckPrice_btn = new javax.swing.JButton();
        user_NumberOfPassengers = new javax.swing.JComboBox<>();
        card_btn = new javax.swing.JRadioButton();
        cash_btn = new javax.swing.JRadioButton();
        bankTrans_btn = new javax.swing.JRadioButton();
        SubmitReservation_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("AirTaxi Reservation");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Origin Station");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Destination Station");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Departure Date & Time");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Number of Passengers");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Payment Method");

        user_OriginStation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_OriginStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almaza Air Base", "Pyramids", "Sheikh-Zayed", "Citadel", "New Administrative Capital" , "Hurghada", "Luxor", "Siwa", "Sharm El Sheikh", "Saint Catherine" }));
        user_OriginStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_OriginStationActionPerformed(evt);
            }
        });

        user_DestinationStation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_DestinationStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almaza Air Base", "Pyramids", "Sheikh-Zayed", "Citadel", "New Administrative Capital" , "Hurghada", "Luxor", "Siwa", "Sharm El Sheikh", "Saint Catherine" }));

        user_DepartureDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        user_DepartureTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_DepartureTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));

        CheckPrice_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CheckPrice_btn.setText("Check Price");
        CheckPrice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPrice_btnActionPerformed(evt);
            }
        });

        user_NumberOfPassengers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_NumberOfPassengers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        user_NumberOfPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_NumberOfPassengersActionPerformed(evt);
            }
        });

        user_PaymentMethod.add(card_btn);
        card_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        card_btn.setText("Card");

        user_PaymentMethod.add(cash_btn);
        cash_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cash_btn.setText("Cash");

        user_PaymentMethod.add(bankTrans_btn);
        bankTrans_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bankTrans_btn.setText("Bank Transfer");
        bankTrans_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTrans_btnActionPerformed(evt);
            }
        });

        SubmitReservation_btn.setBackground(new java.awt.Color(26, 115, 232));
        SubmitReservation_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SubmitReservation_btn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitReservation_btn.setText("Submit Reservation");
        SubmitReservation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitReservation_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("The total price is: ");

        TotalPriceLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CheckPrice_btn)
                            .addGap(93, 93, 93)
                            .addComponent(SubmitReservation_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(user_OriginStation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(user_DestinationStation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(user_DepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(user_DepartureTime, 0, 90, Short.MAX_VALUE)))
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(user_NumberOfPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(card_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(cash_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(bankTrans_btn))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_OriginStation, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(user_NumberOfPassengers))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_DestinationStation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(card_btn)
                        .addComponent(cash_btn)
                        .addComponent(bankTrans_btn)))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_DepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(user_DepartureDate))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckPrice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitReservation_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckPrice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPrice_btnActionPerformed
        // TODO add your handling code here:
        try {
            int originId = user_OriginStation.getSelectedIndex() + 1;
            int destinationId = user_DestinationStation.getSelectedIndex() + 1;
            int passengers = Integer.parseInt(user_NumberOfPassengers.getSelectedItem().toString());

            // POLYMORPHISM ❤️
            TransportationReservation reservation = new Transportation_AirTaxi(user_id, originId, destinationId, 0, passengers);

            double total = reservation.calculatePrice();

            if (total == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Sorry, this AirTaxi route is not available.", 
                    "Invalid Route", 
                    JOptionPane.ERROR_MESSAGE);
                TotalPriceLabel.setText("");
            } else {
                TotalPriceLabel.setText(total + " USD");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_CheckPrice_btnActionPerformed

    private void bankTrans_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTrans_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankTrans_btnActionPerformed

    private void SubmitReservation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitReservation_btnActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Price must be calculated first
            if (TotalPriceLabel.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please check the price first.");
                return;
            }

            // 2. Determine payment method
            String paymentMethod = "";
            if (card_btn.isSelected()) paymentMethod = "Card";
            else if (cash_btn.isSelected()) paymentMethod = "Cash";
            else if (bankTrans_btn.isSelected()) paymentMethod = "Bank Transfer";
            else {
                JOptionPane.showMessageDialog(this, "Please select a payment method.");
                return;
            }

            // 3. Read passenger count, origin, destination
            int passengers = Integer.parseInt(user_NumberOfPassengers.getSelectedItem().toString());
            String origin = user_OriginStation.getSelectedItem().toString();
            String destination = user_DestinationStation.getSelectedItem().toString();

            // Prevent booking the same place
            if (origin.equals(destination)) {
                JOptionPane.showMessageDialog(this, "Origin and Destination cannot be the same.");
                return;
            }

            // 4. Read date + time
            String date = user_DepartureDate.getText().trim();
            String time = user_DepartureTime.getSelectedItem().toString();

            if (date.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the departure date (YYYY-MM-DD).");
                return;
            }

            // 5. Combine into SQL Timestamp
            String dateTime = date + " " + time + ":00";
            java.sql.Timestamp departureTimestamp;

            try {
                departureTimestamp = java.sql.Timestamp.valueOf(dateTime);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid date format. Use YYYY-MM-DD.");
                return;
            }

            // 6. Extract price (remove USD)
            double totalPrice = Double.parseDouble(TotalPriceLabel.getText().replace(" USD", "").trim());

            // 7. Create booking model object
            handleTransportationBookings booking = new handleTransportationBookings(
                    this.user_id,            // logged in user id
                    origin,
                    destination,
                    departureTimestamp,
                    passengers,
                    paymentMethod,
                    totalPrice,
                    "Pending"                // initial status
            );

            // 8. Save into the database
            booking.saveBooking();

            // After successful booking:
            JOptionPane.showMessageDialog(this, 
                "Your AirTaxi booking has been submitted!\nBooking ID: " + booking.getBookingId());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_SubmitReservation_btnActionPerformed

    private void user_OriginStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_OriginStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_OriginStationActionPerformed

    private void user_NumberOfPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_NumberOfPassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_NumberOfPassengersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AirTaxi_Reservation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckPrice_btn;
    private javax.swing.JButton SubmitReservation_btn;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JRadioButton bankTrans_btn;
    private javax.swing.JRadioButton card_btn;
    private javax.swing.JRadioButton cash_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField user_DepartureDate;
    private javax.swing.JComboBox<String> user_DepartureTime;
    private javax.swing.JComboBox<String> user_DestinationStation;
    private javax.swing.JComboBox<String> user_NumberOfPassengers;
    private javax.swing.JComboBox<String> user_OriginStation;
    private javax.swing.ButtonGroup user_PaymentMethod;
    // End of variables declaration//GEN-END:variables
}
