/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Transportation;

import javax.swing.JOptionPane;
import java.sql.Timestamp;
/**
 *
 * @author memo1
 */
public class Monorail_Reservation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Monorail_Reservation.class.getName());

    /**
     * Creates new form Monorail_Reservation
     */
    
    private int user_id;
    public Monorail_Reservation(int user_id) {
        this.user_id = user_id;
        initComponents();
    }
    
    public Monorail_Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user_OriginStation = new javax.swing.JComboBox<>();
        user_DestinationStation = new javax.swing.JComboBox<>();
        user_DepartDate = new javax.swing.JTextField();
        user_DepartTime = new javax.swing.JComboBox<>();
        user_NumOfPassengers = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        display_price_label = new javax.swing.JLabel();
        Submit_btn = new javax.swing.JButton();
        CheckPrice_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Monorail Reservation");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Origin Station");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Destination Station");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Departure Date & Time");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Number of Passengers");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Payment Method");

        user_OriginStation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_OriginStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al Estad", "Hisham Barakat", "Nouri Khattab - Al Azhar University", "Al Hay Al Sabaa", "Free Zone 1", "Free Zone 2", "Al Mushir Tantawy", "Cairo Festival", "Al Shweifat", "Military Hospital", "Hay Al Narges", "Mohamed Naguib", "American University", "Emaar", "Al Nofara Square", "Al Burwa", "Middle Ring Road", "Mohamed Bin Zayed", "Regional Ring Road", "Al Masa Hotel", "Hay Al Wuzarat", "New Administrative Capital" }));

        user_DestinationStation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_DestinationStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Al Estad", "Hisham Barakat", "Nouri Khattab - Al Azhar University", "Al Hay Al Sabaa", "Free Zone 1", "Free Zone 2", "Al Mushir Tantawy", "Cairo Festival", "Al Shweifat", "Military Hospital", "Hay Al Narges", "Mohamed Naguib", "American University", "Emaar", "Al Nofara Square", "Al Burwa", "Middle Ring Road", "Mohamed Bin Zayed", "Regional Ring Road", "Al Masa Hotel", "Hay Al Wuzarat", "New Administrative Capital" }));

        user_DepartDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        user_DepartTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_DepartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00" }));

        user_NumOfPassengers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_NumOfPassengers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5"}));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setText("Card");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setText("Cash");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton3.setText("Bank Transfer");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("The total price is: ");

        display_price_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Submit_btn.setBackground(new java.awt.Color(26, 115, 232));
        Submit_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        Submit_btn.setText("Submit Reservation");
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        CheckPrice_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CheckPrice_btn.setText("Check Price");
        CheckPrice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPrice_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addGap(338, 338, 338)
                        .addComponent(jLabel5)
                        .addGap(493, 493, 493))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(user_DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(user_DepartTime, 0, 95, Short.MAX_VALUE))
                                                .addComponent(user_DestinationStation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(user_OriginStation, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(230, 230, 230)
                                        .addComponent(CheckPrice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(user_NumOfPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jRadioButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(display_price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Submit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_OriginStation, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(user_NumOfPassengers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_DestinationStation, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_DepartTime)
                    .addComponent(user_DepartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(display_price_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckPrice_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        // TODO add your handling code here:                                      
        try {
            int originId = user_OriginStation.getSelectedIndex() + 1;
            int destinationId = user_DestinationStation.getSelectedIndex() + 1;
            int passengerCount = Integer.parseInt(user_NumOfPassengers.getSelectedItem().toString());
            int userId = this.user_id;

            String origin = user_OriginStation.getSelectedItem().toString();
            String destination = user_DestinationStation.getSelectedItem().toString();

            // Payment method
            String paymentMethod = "";
            if (jRadioButton1.isSelected()) paymentMethod = "Card";
            else if (jRadioButton2.isSelected()) paymentMethod = "Cash";
            else if (jRadioButton3.isSelected()) paymentMethod = "Bank Transfer";

            // Input validation
            if (originId == destinationId) {
                JOptionPane.showMessageDialog(null, "Origin and destination stations cannot be the same.");
                return;
            }

            String departDateStr = user_DepartDate.getText();
            String departTimeStr = user_DepartTime.getSelectedItem().toString();

            if (departDateStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a departure date.");
                return;
            }

            if (paymentMethod.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select a payment method.");
                return;
            }

            // Parse date/time safely
            java.sql.Timestamp departureTimestamp;
            try {
                departureTimestamp = java.sql.Timestamp.valueOf(departDateStr + " " + departTimeStr + ":00");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "Invalid date or time format. Use YYYY-MM-DD for date.");
                return;
            }

            // Calculate price
            Transportation_Monorail bookingPrice = new Transportation_Monorail(
                    userId, originId, destinationId, 0, passengerCount
            );
            double totalPrice = bookingPrice.calculatePrice();

            // Create booking object
            handleTransportationBookings booking = new handleTransportationBookings(
                    userId, origin, destination, departureTimestamp, passengerCount, paymentMethod, totalPrice, "Pending"
            );

            // Save booking
            booking.saveBooking();

            // Display price
            display_price_label.setText(totalPrice + " EGP");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }


    }//GEN-LAST:event_Submit_btnActionPerformed

    private void CheckPrice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPrice_btnActionPerformed
        // TODO add your handling code here:
        int originId = user_OriginStation.getSelectedIndex() + 1;
        int destinationId = user_DestinationStation.getSelectedIndex() + 1;

        // Get number of passengers
        int passengerCount = Integer.parseInt(user_NumOfPassengers.getSelectedItem().toString());

        // Create monorail booking instance
        Transportation_Monorail booking = new Transportation_Monorail(0, originId, destinationId, 0, passengerCount);

        // Calculate total price
        double totalPrice = booking.calculatePrice();

        // Display the price in the label
        display_price_label.setText(totalPrice + " EGP");
    }//GEN-LAST:event_CheckPrice_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Monorail_Reservation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckPrice_btn;
    private javax.swing.JButton Submit_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel display_price_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField user_DepartDate;
    private javax.swing.JComboBox<String> user_DepartTime;
    private javax.swing.JComboBox<String> user_DestinationStation;
    private javax.swing.JComboBox<String> user_NumOfPassengers;
    private javax.swing.JComboBox<String> user_OriginStation;
    // End of variables declaration//GEN-END:variables
}
