/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Tickets;

import java.util.List;

/**
 *
 * @author memo1
 */
public class My_Tickets_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(My_Tickets_Form.class.getName());

    /**
     * Creates new form My_Tickets_Form
     */
    
    int user_id;
    
    public My_Tickets_Form(int user_id) {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        this.user_id = user_id;
    }
    
    public My_Tickets_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        monorail_btn = new javax.swing.JButton();
        airtaxi_btn = new javax.swing.JButton();
        gem_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setText("My Tickets");

        monorail_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Tickets/monorail_ticket_icon_transparent.png"))); // NOI18N
        monorail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monorail_btnActionPerformed(evt);
            }
        });

        airtaxi_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Tickets/AirTaxi_ticket_icon_transparent.png"))); // NOI18N
        airtaxi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airtaxi_btnActionPerformed(evt);
            }
        });

        gem_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Tickets/GEM_ticket_icon_transparent.png"))); // NOI18N
        gem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gem_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monorail_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(airtaxi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGap(78, 78, 78)
                .addComponent(gem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monorail_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airtaxi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gem_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void openMonorailTickets() {
    // Retrieve monorail tickets for the current user
        List<handleTickets> tickets = handleTickets.getMonorailBookings(user_id);

        // Convert ticket IDs to String list
        List<String> bookingIds = new java.util.ArrayList<>();
        for (handleTickets t : tickets) {
            bookingIds.add(String.valueOf(t.getTicketId()));
        }

        // Open the Monorail_Display_Tickets JFrame with these booking IDs
        Monorail_Display_Tickets displayFrame = new Monorail_Display_Tickets(bookingIds);
        displayFrame.setVisible(true);
    }
    
    private void openAirTaxiTickets() {
        // Retrieve Air Taxi tickets for the current user
        List<handleTickets> tickets = handleTickets.getAirTaxiBookings(user_id);

        // Convert to booking IDs
        List<String> bookingIds = new java.util.ArrayList<>();
        for (handleTickets t : tickets) {
            bookingIds.add(String.valueOf(t.getTicketId()));
        }

        // Open the Air Taxi display form with these booking IDs
        AirTaxi_Display_Tickets displayFrame = new AirTaxi_Display_Tickets(bookingIds);
        displayFrame.setVisible(true);
    }



    private void openGEMTickets() {
        // Retrieve GEM tickets for the current user
        List<handleTickets> tickets = handleTickets.getTouristSiteBookings(user_id);

        // Convert ticket IDs to String list
        List<String> bookingIds = new java.util.ArrayList<>();
        for (handleTickets t : tickets) {
            bookingIds.add(String.valueOf(t.getTicketId()));
        }

        // Open the Monorail_Display_Tickets JFrame with these booking IDs
        GEM_Display_Tickets displayFrame = new GEM_Display_Tickets(bookingIds);
        displayFrame.setVisible(true);
    }

    
    private void monorail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monorail_btnActionPerformed
        // TODO add your handling code here:
        openMonorailTickets();
    }//GEN-LAST:event_monorail_btnActionPerformed

    private void airtaxi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airtaxi_btnActionPerformed
        // TODO add your handling code here:
        openAirTaxiTickets();
    }//GEN-LAST:event_airtaxi_btnActionPerformed

    private void gem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gem_btnActionPerformed
        // TODO add your handling code here:
        openGEMTickets();
    }//GEN-LAST:event_gem_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new My_Tickets_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airtaxi_btn;
    private javax.swing.JButton gem_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton monorail_btn;
    // End of variables declaration//GEN-END:variables
}
