/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Egypt_2030_Text;

import java.awt.Color;

/**
 *
 * @author memo1
 */
public class Egypt2030_fr extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Egypt2030_fr.class.getName());

    /**
     * Creates new form Egypt2030_fr
     */
    public Egypt2030_fr() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Wrapping
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        
        // Read Only
        jTextArea1.setEditable(false);
        
        // Transparent Background
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new Color(0, 0, 0, 0));
        jTextArea1.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea1.setSelectionColor(new Color(51, 153, 255));  
        jTextArea1.setSelectedTextColor(Color.WHITE);
        
        ///////////////////////
        
        // Wrapping
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        
        // Read Only
        jTextArea2.setEditable(false);
        
        // Transparent Background
        jTextArea2.setOpaque(false);
        jTextArea2.setBackground(new Color(0, 0, 0, 0));
        jTextArea2.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea2.setSelectionColor(new Color(51, 153, 255));  
        jTextArea2.setSelectedTextColor(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Le rôle du Président Al-Sissi dans La Nouvelle République");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Depuis 2014, Son Excellence le Président Abdel Fattah Al-Sissi a assumé la responsabilité de diriger l'Égypte à un moment historique crucial, guidant le pays avec sagesse et détermination pour sauver ses institutions et rétablir la stabilité, posant ainsi les bases d’une renaissance moderne qui prépare le terrain aux ambitions de la Vision Égypte 2030.\n\nSous sa direction ferme, d’imposants projets nationaux ont été lancés, transformant l'Égypte en un chantier de construction permanent : infrastructures avancées, sécurité énergétique sans précédent, nouvelles villes, et développement s’étendant du nord au sud du pays.\n\nSon Excellence a offert un modèle de leadership combinant prise de décision ferme et rapidité d’exécution, rétablissant la confiance dans la capacité du pays à se relever et renforçant l’espoir d’un avenir plus lumineux pour l’Égypte et son peuple.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Forces armées égyptiennes : bouclier et partenaire du développement");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Les Forces armées égyptiennes constituent le bouclier solide de la nation, protégeant la sécurité et la stabilité de l’Égypte, et symbolisent la discipline ainsi que la force nationale. Depuis 2014, elles jouent un rôle central dans le maintien de la sécurité de l’État et le soutien au développement global, devenant un partenaire clé dans la mise en œuvre de la Vision Égypte 2030.\n\nL’Autorité d’ingénierie des Forces armées a réalisé d’importants projets d’infrastructure, incluant routes, ponts, tunnels et stations de traitement d’eau, et a contribué à la construction de nouvelles villes.\n\nProjets de développement national : soutien à la nouvelle capitale administrative, à la ville nouvelle d’Alamein, et à l’initiative « Hayah Karima ».\n\nRenforcement de la sécurité et de la stabilité : protection des frontières et maintien de la stabilité intérieure, permettant la mise en œuvre efficace des plans de développement.\n\nGrâce à ces efforts, les Forces armées démontrent qu’elles ne sont pas seulement une force défensive, mais un pilier fondamental de la croissance et du développement national, jouant un rôle central dans la réalisation de la Vision Égypte 2030 et assurant un avenir durable pour les générations à venir.");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("La Nouvelle République : Leadership, Réalisations et Vision 2030");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Egypt_2030_Text/president_military_suit.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Egypt2030_fr().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
