/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Egypt_2030_Text;
import java.awt.Color;


/**
 *
 * @author memo1
 */
public class Egypt2030_ar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Egypt2030_ar.class.getName());

    /**
     * Creates new form Egypt2030_ar
     */
    public Egypt2030_ar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Right to Left
        jTextArea1.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        
        // Wrapping
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        
        // Read Only
        jTextArea1.setEditable(false);
        
        // Transparent Background
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new Color(0, 0, 0, 0));
        jTextArea1.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea1.setSelectionColor(new Color(51, 153, 255));  
        jTextArea1.setSelectedTextColor(Color.WHITE);
        
        
        ///////////////////////
        jTextArea2.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        
        // Wrapping
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        
        // Read Only
        jTextArea2.setEditable(false);
        
        // Transparent Background
        jTextArea2.setOpaque(false);
        jTextArea2.setBackground(new Color(0, 0, 0, 0));
        jTextArea2.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea2.setSelectionColor(new Color(51, 153, 255));  
        jTextArea2.setSelectedTextColor(Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("دور فخامة الرئيس عبدالفتاح السيسي في بناء مصر الحديثة");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("منذ عام 2014 تولّى فخامة الرئيس عبدالفتاح السيسي مسؤولية قيادة مصر في لحظة تاريخية فارقة، فقاد الدولة بحكمة وحزم لإنقاذ مؤسساتها واستعادة استقرارها، ليضع أسس النهضة الحديثة التي تمهد لطموحات رؤية مصر 2030.\nوبقيادته القوية انطلقت مشروعات قومية شاهقة، وتحوّلت مصر إلى ورشة بناء لا تتوقف: بنية تحتية متطورة، أمن طاقي غير مسبوق، مدن جديدة، وتنمية تمتد من أقصى الشمال إلى أقصى الجنوب.\nلقد قدّم فخامته نموذجًا للقيادة التي تجمع بين قوة القرار وسرعة الإنجاز، مما أعاد الثقة في قدرة الدولة على النهوض، ورسّخ الأمل في مستقبل أكثر إشراقًا لمصر وشعبها.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("القوات المسلحة المصرية: درع الوطن وشريك التنمية");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("تُعد القوات المسلحة المصرية الدرع الحصين الذي يحمي أمن مصر واستقرارها، وهي رمز الانضباط والقوة الوطنية. منذ 2014، لعبت دورًا محوريًا في الحفاظ على أمن الدولة ودعم مسيرة التنمية الشاملة، لتصبح شريكًا رئيسيًا في تنفيذ رؤية مصر 2030.\n\n- الهيئة الهندسية للقوات المسلحة نفذت مشروعات ضخمة في البنية التحتية: طرق، كباري، أنفاق، ومحطات مياه، وساهمت في بناء المدن الجديدة.\n\n- مشروعات التنمية القومية: دعم العاصمة الإدارية الجديدة، مدينة العلمين الجديدة، ومبادرة “حياة كريمة”.\n\n- تعزيز الأمن والاستقرار: حماية الحدود وتأمين الاستقرار الداخلي، مما أتاح تنفيذ خطط التنمية بثقة.\n\nبهذه الجهود، تؤكد القوات المسلحة أنها ليست مجرد قوة دفاعية، بل ركيزة أساسية للنمو والتطوير الوطني، ومكوّن أساسي لتحقيق رؤية مصر 2030 واستدامة المستقبل للأجيال القادمة.");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Egypt_2030_Text/president_military_suit.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("الجمهوريه الجديده: القيادة والإنجازات ورؤية 2030");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Egypt2030_ar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
