/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Egypt_2030_Text;

import java.awt.Color;

/**
 *
 * @author memo1
 */
public class Egypt2030_es extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Egypt2030_es.class.getName());

    /**
     * Creates new form Egypt2030_es
     */
    public Egypt2030_es() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Wrapping
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        
        // Read Only
        jTextArea1.setEditable(false);
        
        // Transparent Background
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new Color(0, 0, 0, 0));
        jTextArea1.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea1.setSelectionColor(new Color(51, 153, 255));  
        jTextArea1.setSelectedTextColor(Color.WHITE);
        
        ///////////////////////
        
        // Wrapping
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        
        // Read Only
        jTextArea2.setEditable(false);
        
        // Transparent Background
        jTextArea2.setOpaque(false);
        jTextArea2.setBackground(new Color(0, 0, 0, 0));
        jTextArea2.setBorder(null);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null); 

        // Selection highlight restored
        jTextArea2.setSelectionColor(new Color(51, 153, 255));  
        jTextArea2.setSelectedTextColor(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Desde el año 2014, Su Excelencia el presidente Abdel Fattah Al-Sisi asumió la responsabilidad de dirigir Egipto en un momento histórico decisivo. Con sabiduría y determinación, condujo al Estado para salvar sus instituciones y restaurar su estabilidad, estableciendo las bases del renacimiento moderno que prepara el camino hacia las aspiraciones de la Visión Egipto 2030.\n\nBajo su firme liderazgo, se pusieron en marcha grandes proyectos nacionales y Egipto se transformó en un taller de construcción incesante: una infraestructura desarrollada, una seguridad energética sin precedentes, nuevas ciudades y un desarrollo que se extiende desde el extremo norte hasta el extremo sur.\n\nSu Excelencia ofreció un modelo de liderazgo que combina la fuerza en la toma de decisiones con la rapidez en la ejecución, lo que devolvió la confianza en la capacidad del Estado para avanzar y consolidó la esperanza en un futuro más próspero para Egipto y su pueblo.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("El papel del presidente Al-Sisi en la Nueva República.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Las Fuerzas Armadas Egipcias: escudo y socio en el desarrollo.");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Las Fuerzas Armadas Egipcias constituyen el escudo sólido que protege la seguridad y la estabilidad de Egipto, y representan un símbolo de disciplina y fuerza nacional. Desde 2014, han desempeñado un papel fundamental en la preservación de la seguridad del Estado y en el apoyo al proceso de desarrollo integral, convirtiéndose en un socio principal en la implementación de la Visión Egipto 2030.\n\n- La Autoridad de Ingeniería de las Fuerzas Armadas ha ejecutado grandes proyectos de infraestructura: carreteras, puentes, túneles, estaciones de agua, y ha contribuido a la construcción de nuevas ciudades.\n- Proyectos de desarrollo nacional: apoyo a la Nueva Capital Administrativa, la ciudad de New Alamein y la iniciativa “Vida Digna”.\n- Reforzamiento de la seguridad y la estabilidad: protección de las fronteras y garantía de la estabilidad interna, lo que ha permitido ejecutar los planes de desarrollo con confianza.\n\nCon estos esfuerzos, las Fuerzas Armadas confirman que no son únicamente una fuerza defensiva, sino un pilar esencial del crecimiento y del desarrollo nacional, y un componente clave para lograr la Visión Egipto 2030 y garantizar la sostenibilidad del futuro para las generaciones venideras.");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("La Nueva República: liderazgo, logros y la Visión 2030");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Egypt_2030_Text/president_military_suit.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 141, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Egypt2030_es().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
